# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e9ace606af719fa0a4a1b0ef3a03f5e342d4e9e425a89c06b2f424994960153108595a74a50de6524202bc4016ed34ac057174f56158911c71e1a3ecf25d609

test:
  secret_key_base: e01e30628c35b01e2497c5d6691ca16517713ca15b6006d4deae4eb9fece8019093e88b7415ad9e048da0b97ecec8788b26d90312d6b53c0f1ab2dfb57c92750

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
